/**
 * build-map.mjs — offline build step for the Home Base mini-map.
 *
 * Reads real coastline data (Natural Earth land-50m via world-atlas),
 * keeps only the polygons for Java + Madura, projects them with an
 * equirectangular projection into a 400x180 viewBox, and writes a
 * static SVG path to lib/map-data.ts. No runtime dependency.
 *
 * Usage: npm run map
 */

import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoEquirectangular } from "d3-geo";

// Java spans ~105.0E-114.4E, ~-5.9 to -8.8. Jakarta: 106.816E, -6.2S.
const MIN_LNG = 105;
const MAX_LNG = 114.4; // excludes Bali, keeps Madura
const MIN_LAT = -9.2;
const MAX_LAT = -5.5;
const MIN_AREA = 0.02; // deg^2 — drops islets (Kepulauan Seribu, Karimunjawa, ...)

const topo = JSON.parse(
  readFileSync("node_modules/world-atlas/land-50m.json", "utf8")
);
const land = feature(topo, topo.objects.land);
const allPolygons =
  land.type === "FeatureCollection"
    ? land.features.flatMap((f) => f.geometry.coordinates)
    : land.geometry.coordinates;

const kept = allPolygons.filter((poly) => {
  const ring = poly[0];
  let minLng = 180;
  let maxLng = -180;
  let minLat = 90;
  let maxLat = -90;
  for (const [lng, lat] of ring) {
    if (lng < minLng) minLng = lng;
    if (lng > maxLng) maxLng = lng;
    if (lat < minLat) minLat = lat;
    if (lat > maxLat) maxLat = lat;
  }
  const cx = (minLng + maxLng) / 2;
  const cy = (minLat + maxLat) / 2;
  const area = (maxLng - minLng) * (maxLat - minLat);
  return (
    cx >= MIN_LNG &&
    cx <= MAX_LNG &&
    cy >= MIN_LAT &&
    cy <= MAX_LAT &&
    area >= MIN_AREA
  );
});

const collection = {
  type: "FeatureCollection",
  features: kept.map((coordinates) => ({
    type: "Feature",
    properties: {},
    geometry: { type: "Polygon", coordinates },
  })),
};

const projection = geoEquirectangular().fitExtent(
  [
    [14, 18],
    [386, 164],
  ],
  collection
);

const pathParts = [];
for (const feat of collection.features) {
  for (const ring of feat.geometry.coordinates) {
    const pts = ring.map(([lng, lat]) => projection([lng, lat]));
    pathParts.push(
      `M ${pts.map((p) => `${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(" L ")} Z`
    );
  }
}

const jakarta = projection([106.816, -6.2]);

const output = `// AUTO-GENERATED by scripts/build-map.mjs - do not edit by hand.
// Source: Natural Earth land-50m (world-atlas). Marker: Jakarta 106.816E, -6.2S.
export const JAVA_MAP_PATH = "${pathParts.join(" ")}";
export const JAKARTA_POINT = { x: ${jakarta[0].toFixed(1)}, y: ${jakarta[1].toFixed(1)} } as const;
`;

writeFileSync("lib/map-data.ts", output);
console.log(
  `Wrote lib/map-data.ts — ${kept.length} polygons, Jakarta at (${jakarta[0].toFixed(1)}, ${jakarta[1].toFixed(1)})`
);
